### ISSUE TITLE
Add tcp states and tcp retrans, tcp drop metrics

### ISSUE THREAD

**Issue by Colstuwjx** [cloudflare/ebpf_exporter#128]
For now, we only have tcp sync example, how about add [tcp retrans](https://github.com/iovisor/bcc/blob/master/tools/tcpretrans.py), [tcp state](https://github.com/iovisor/bcc/blob/master/tools/tcpstates.py) and [tcp drop](https://github.com/iovisor/bcc/blob/master/tools/tcpdrop.py) metrics? 

It will help us get a more clear tcp flow view.

**Comment by bobrik** [comment]
Feel free to open PRs.
