### ISSUE TITLE
Map events to systemd units

### ISSUE THREAD

**Issue by bobrik** [cloudflare/ebpf_exporter#13]
Currently we have an example where we map PID to command:

```c
bpf_get_current_comm(&key.command, sizeof(key.command));
```

Most (if not all) modern distributions run on systemd, where services belong to units. Commands alone sometimes do not have enough context to map them to logical services.

cAdvisor has cgroup name in `id` label, which seems a lot more usable for long term metric reporting:

```
container_cpu_user_seconds_total{id="/system.slice/cron.service",instance="myhost",job="cadvisor"} 43153.13
```

We should find a way to do the same.

Having PIDs in map keys and then remapping them to systemd units in userspace does not work, because PIDs can be reused across units. We can probably supply a map with PID -> unit mapping and update that dynamically (cgroup tracepoints may work for this), but that seems a bit involved, unless it works transparently to the user.

List of PIDs per service can be obtained in userspace from sysfs:

```
$ cat /sys/fs/cgroup/systemd/system.slice/cron.service/cgroup.procs
5726
```

cc @dqminh

**Comment by bobrik** [comment]
Related: https://github.com/iovisor/bcc/issues/1119.

**Comment by zuzzas** [comment]
@bobrik 
Hi! Have there been any new developments in the year and a half?

**Comment by bobrik** [comment]
@zuzzas, does #70 address your needs? It [should work](https://github.com/torvalds/linux/commit/bf6fa2c893c5237b48569a13fa3c673041430b6c) on Linux 4.18 and newer.

**Comment by zuzzas** [comment]
Thank you! I'll continue the experiments on the weekend. Will provide feedback.

**Comment by zuzzas** [comment]
That leaves one last problem. An OOM killer routine executes in the context of a task that triggered out of memory condition (memory fault). If I were to dynamically instrument it, there is a reference to a task struct which is **being killed**, from which I can get its PID and, perhaps, something else? Therefore, it's important to have a fast PID-to-cgroup mapping somewhere.

You've proposed a [solution](https://github.com/iovisor/bcc/issues/1119#issuecomment-389076559) 2 years ago, have you had any luck with this? Or, perhaps, there is another way?

**Comment by bobrik** [comment]
It may be possible to do what `bpf_get_current_cgroup_id()` does, since it operates on `task_struct` under the hood:

* https://elixir.bootlin.com/linux/v5.4/source/kernel/bpf/helpers.c#L316

**Comment by zuzzas** [comment]
But that would require recompiling the kernel with a new function since eBPF programs are allowed to operate on a subset (helper) of functions?

**Comment by bobrik** [comment]
Not necessarily, you can do this:

```c
#include <linux/cgroup.h>

// Do What bpf_get_current_cgroup_id() helper does, sans rcu_derference
static u64 task_cgroup_id(struct task_struct * task) {
    // This bit happens with rcu_derference in bpf_get_current_cgroup_id:
    // * https://elixir.bootlin.com/linux/v5.4/source/include/linux/cgroup.h#L451
    struct css_set *css = task->cgroups;

    return css->dfl_cgrp->kn->id.id;
}
```

I honestly don't know if anything bad happens due to lack of `rcu_dereference()`, but verifier is happy.

Does this work for you?

**Comment by zuzzas** [comment]
I'll give it a definite go on the weekend. Thank you!
