### ISSUE TITLE
Cachestat examples no longer working

### ISSUE THREAD

**Issue by rogercoll** [cloudflare/ebpf_exporter#132]
Since Linux 5.14, I got the following error while trying to run the `cachestat` examples:

```
[root@myarch ebpf_exporter]# ./ebpf_exporter.x86_64 --config.file=examples/cachestat.yaml 
cannot attach kprobe, probe entry may not exist
2022/01/30 10:00:44 Error attaching exporter: failed to attach to program "cachestat": failed to attach kprobes: failed to attach probe "account_page_dirtied" to "do_count": failed to attach BPF kprobe: no such file or directory
```

The reason of the failure is because `account_page_dirtied` function was changed to static in https://github.com/torvalds/linux/commit/6e1cae881a0646f31fe2bda90297d820da1137eb , thus it can can only be used within the file. In addition, a few commits after it was renamed to `folio_account_dirtied` (https://github.com/torvalds/linux/commit/203a31516616111b8eaaf00c16fa3fcaa25e6f81), but still unusable (kernel 5.17-rc1):

```
[root@myarch ebpf_exporter]# ./ebpf_exporter.x86_64 --config.file=examples/cachestat.yaml 
cannot attach kprobe, probe entry may not exist
2022/01/30 10:06:46 Error attaching exporter: failed to attach to program "cachestat": failed to attach kprobes: failed to attach probe "folio_account_dirtied" to "do_count": failed to attach BPF kprobe: no such file or directory
```

I would purpose to remove this kprobe from the example files, or to change it to `folio_mark_dirty` although some of the accesses to this function won't end up marking the page as dirty.

I'd be happy to submit a PR if that'd be welcome!

Cheers

**Comment by bobrik** [comment]
On my machine `folio_account_dirtied` is actually available on 5.17-rc4 (aarch64 compiled with Clang):

```
ivan@vm:~$ cat /proc/kallsyms | fgrep folio_account_dirtied
0000000000000000 t folio_account_dirtied
```

BCC doesn't really address this:

* https://github.com/iovisor/bcc/commit/61087b961716ad96d1d7d9711a53202b9e88b990

There's a tracepoint there, which has been renamed in v5.16:

* https://github.com/torvalds/linux/commit/b9b0ff61eef51469eae962b80bae094ce2c8c2a5

Maybe the best course of action is to target 5.15 LTS by default and have a comment showing how to make it work on older/newer kernels, if necessary.

Feel free to make a PR.

**Comment by rogercoll** [comment]
@bobrik Makes sense to me. Small PR that adds a comment #133

**Comment by bobrik** [comment]
If anyone wants to revive cachestat, please go for it. We switched to libbpf, so hopefully this will be easier now.
