### ISSUE TITLE
Support fentry/fexit to replace kprobe/kretprobe

### ISSUE THREAD

**Issue by wenlxie** [cloudflare/ebpf_exporter#143]
We have a requirement that need to use fentry/fexit as much as possible to replace kprobe, 
But some of our nodes' kernel are still in old kernel and not support fentry. 
That means we need to solve following issues:
1. In node with old kernel, we need to use kprobe
2. In node with new kernel, we can use fentry to replace kprobe
3. Pods runs on these nodes with the same pod spec. 

One of the solution I am thinking is:
1. Add a kernel version limitation to the programs, if current program not met the requirements, then it will not be loaded
2. We will provide two programs for the same requirements but with different implementation, one is by fentry and another is kprobe. Only one will be loaded because of kernel version limitation configured 

@bobrik  Any suggestion for this? 
Thanks for your time.

**Comment by bobrik** [comment]
It looks like `fentry` is also not yet available on arm64 even in 6.1-rc1. This patch is needed:

* https://patchwork.kernel.org/project/netdevbpf/cover/20220913162732.163631-1-xukuohai@huaweicloud.com/

I added `fentry` benchmarks in #144 and it looks much better than `kprobe` (as expected).

@zuzzas has #136 with both graceful handling for programs that cannot be loaded and kernel constraints.

I'll try to find some time to think how to make this work with the least amount of friction.

**Comment by wenlxie** [comment]
The performance of `fentry` looks really amazing
@bobrik Many thanks for the infos. 
Kernel constraints  is a common requirements in Cloud.  Patiently wait  for the solutions.  Thanks

**Comment by bobrik** [comment]
Is having the same config across the whole fleet the right idea to begin with?

What if somebody wants to load probes based on hardware, like NICs? What if there's something CPU model specific? We can't keep adding checks to ebpf_exporter to accommodate every situation.

I think there's a natural fit for external configuration management here. For physical hardware it might be whatever you use to configure the rest of it (we use Salt). For k8s you can write some sort of script that would do the equivalent work of checking any conditions you want for every program you have.

It can be as simple and as customizable as a python script:

```python
#!/usr/bin/env python3

import yaml
import platform
import packaging.version


def min_kernel_version(min_version):
    min_version = packaging.version.parse(min_version)
    running_version = packaging.version.parse(platform.release().split("-")[0])
    return running_version >= min_version


PROGRAMS = {
    "timers": [],
    "cgroup": [min_kernel_version("5.15")],
}

if __name__ == "__main__":
    enabled = []
    for name, checks in PROGRAMS.items():
        if not all(checks):
            continue
        enabled.append(name)

    programs = []
    for name in enabled:
        with open(f"examples/{name}.yaml", "r") as f:
            config = yaml.load(f, Loader=yaml.SafeLoader)
            programs.append(config["programs"][0])

    print(yaml.dump({"programs": programs}))
```

**Comment by wenlxie** [comment]
@bobrik Thanks
You are right, we can't check for all conditions. 
I can add such kind of checks into a startup script.

**Comment by bobrik** [comment]
With #145 `fentry` should be supported. Let me know if you see any issues.
