### ISSUE TITLE
Metrics of Exited Processes Still in BPF Map after Running ebpf_exporter for Extended Periods

### ISSUE THREAD

**Issue by ZhangYet** [cloudflare/ebpf_exporter#185]
After running ebpf_exporter for an extended time, some processes exit, but their metrics remain in the BPF map. For example, using [biolatency](https://github.com/cloudflare/ebpf_exporter/blob/master/examples/biolatency.bpf.c) to monitor biolatency, if a process A is being monitored and exits after a few minutes, A's metric still persists(in the bio_latency_seconds map). How can these metrics be removed from the BPF map?

**Comment by bobrik** [comment]
Did you modify `biolatency` to make it track per pid? The example doesn't differentiate between processes at all. It would be good if you could describe what exactly you're trying to do.

In general, this is just how prometheus metrics work: they accumulate forever and there is no cleanup. You are expected to use metrics for things that have long lifetimes (think cgroups, _maybe_ `comm`), not short lived high churn stuff (think `pid`).

If you do end up in a situation where you want to clear all metrics, the simplest way to do this is to restart `ebpf_exporter`.

**Comment by ZhangYet** [comment]
I did modify biolatancy to make it track per pid. 
One of my friends came out with a resolution:  clean the entry when a pid exits.
