### ISSUE TITLE
how to clean the result every 10 minutes

### ISSUE THREAD

**Issue by summerzhou2011** [cloudflare/ebpf_exporter#199]
after launching the ebpf_exporter program, many metrics will be generated. 
If I want to clean the result , I have to restart the ebpf_exporter program. 
Are there some paramers  in .Yaml file to clean  the result  every some minutes?
I have tried the following  paramers but did not work.  
scrape_interval
empty_interval
reset_interval
flush_interval
flush_duration
scrape_interval
evaluation_interval
empty_interval
reset_interval
ebpf_flush_interval_seconds

any suggestion will be appreciated, thanks,

**Comment by bobrik** [comment]
Why do you need to clear metrics?

**Comment by summerzhou2011** [comment]
for example : we want to check the latency of tcp connect more than 20ms.  we  got many records and most of them may be display one time. with the time past,  many many records was  valueless.

**Comment by bobrik** [comment]
How do you query the data? Do you have a screenshot showing the issue?

**Comment by summerzhou2011** [comment]
# HELP ebpf_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which ebpf_exporter was built.
# TYPE ebpf_exporter_build_info gauge
ebpf_exporter_build_info{branch="",goversion="go1.19.2",revision="",version=""} 1
# HELP ebpf_exporter_ebpf_programs Info about ebpf programs
# TYPE ebpf_exporter_ebpf_programs gauge
ebpf_exporter_ebpf_programs{function="trace_close",program="tcpconnlat",tag="d0547f6f210dd8e0"} 1
ebpf_exporter_ebpf_programs{function="trace_connect",program="tcpconnlat",tag="eba78122be61aeb6"} 1
ebpf_exporter_ebpf_programs{function="trace_exit",program="tcpconnlat",tag="f51e96a6c3b13e12"} 1
ebpf_exporter_ebpf_programs{function="trace_tcp_rcv_state_process",program="tcpconnlat",tag="250422f627501c4"} 1
# HELP ebpf_exporter_enabled_programs The set of enabled programs
# TYPE ebpf_exporter_enabled_programs gauge
ebpf_exporter_enabled_programs{name="tcpconnlat"} 1
# HELP ebpf_exporter_tcpconnlat_ipv4 tcp4 connection latency(ms)
# TYPE ebpf_exporter_tcpconnlat_ipv4 counter
ebpf_exporter_tcpconnlat_ipv4{dst_addr="0.0.0.0",dst_port="9099",family="10",pid="3992906",proc_name="jmxExport",sst_addr="127.0.0.6",ts="0"} 1.307811699e+10
ebpf_exporter_tcpconnlat_ipv4{dst_addr="0.0.0.0",dst_port="9099",family="10",pid="8733",proc_name="kubelet",sst_addr="127.0.0.6",ts="0"} 2.7892224739e+10
ebpf_exporter_tcpconnlat_ipv4{dst_addr="10.39.111.197",dst_port="80",family="2",pid="2212758",proc_name="http-nio-8080-e",sst_addr="29.42.47.110",ts="0"} 28268
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33179",family="2",pid="2787041",proc_name="prometheus-http",sst_addr="127.0.0.1",ts="0"} 51
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33205",family="2",pid="666580",proc_name="prometheus-http",sst_addr="127.0.0.1",ts="0"} 48
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33249",family="2",pid="2770220",proc_name="prometheus-http",sst_addr="127.0.0.1",ts="0"} 39
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="1781405",proc_name="prometheus-http",sst_addr="127.0.0.1",ts="0"} 34
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3424090",proc_name="java",sst_addr="127.0.0.1",ts="0"} 76
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3425536",proc_name="java",sst_addr="127.0.0.1",ts="0"} 75
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3428999",proc_name="java",sst_addr="127.0.0.1",ts="0"} 107
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3430483",proc_name="java",sst_addr="127.0.0.1",ts="0"} 69
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3433990",proc_name="java",sst_addr="127.0.0.1",ts="0"} 90
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3435360",proc_name="java",sst_addr="127.0.0.1",ts="0"} 94
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3440499",proc_name="java",sst_addr="127.0.0.1",ts="0"} 81
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3441979",proc_name="java",sst_addr="127.0.0.1",ts="0"} 67
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3445518",proc_name="java",sst_addr="127.0.0.1",ts="0"} 98
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3447014",proc_name="java",sst_addr="127.0.0.1",ts="0"} 95
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3450553",proc_name="java",sst_addr="127.0.0.1",ts="0"} 81
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3451882",proc_name="java",sst_addr="127.0.0.1",ts="0"} 107
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3455630",proc_name="java",sst_addr="127.0.0.1",ts="0"} 67
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3458940",proc_name="java",sst_addr="127.0.0.1",ts="0"} 104
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3461689",proc_name="java",sst_addr="127.0.0.1",ts="0"} 97
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3463760",proc_name="java",sst_addr="127.0.0.1",ts="0"} 112
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3466610",proc_name="java",sst_addr="127.0.0.1",ts="0"} 91
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3468787",proc_name="java",sst_addr="127.0.0.1",ts="0"} 135
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3472010",proc_name="java",sst_addr="127.0.0.1",ts="0"} 76
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3473782",proc_name="java",sst_addr="127.0.0.1",ts="0"} 72
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3478349",proc_name="java",sst_addr="127.0.0.1",ts="0"} 77
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3480412",proc_name="java",sst_addr="127.0.0.1",ts="0"} 68
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3483445",proc_name="java",sst_addr="127.0.0.1",ts="0"} 94
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3485662",proc_name="java",sst_addr="127.0.0.1",ts="0"} 88
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3488406",proc_name="java",sst_addr="127.0.0.1",ts="0"} 52
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3490107",proc_name="java",sst_addr="127.0.0.1",ts="0"} 97
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3495365",proc_name="java",sst_addr="127.0.0.1",ts="0"} 90
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3496519",proc_name="java",sst_addr="127.0.0.1",ts="0"} 76
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3500693",proc_name="java",sst_addr="127.0.0.1",ts="0"} 112
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3502457",proc_name="java",sst_addr="127.0.0.1",ts="0"} 97
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3506132",proc_name="java",sst_addr="127.0.0.1",ts="0"} 75
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3507503",proc_name="java",sst_addr="127.0.0.1",ts="0"} 134
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3511649",proc_name="java",sst_addr="127.0.0.1",ts="0"} 112
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3514746",proc_name="java",sst_addr="127.0.0.1",ts="0"} 89
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3518490",proc_name="java",sst_addr="127.0.0.1",ts="0"} 92
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3519888",proc_name="java",sst_addr="127.0.0.1",ts="0"} 86
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3523110",proc_name="java",sst_addr="127.0.0.1",ts="0"} 106
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3524639",proc_name="java",sst_addr="127.0.0.1",ts="0"} 96
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3527811",proc_name="java",sst_addr="127.0.0.1",ts="0"} 112
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3529109",proc_name="java",sst_addr="127.0.0.1",ts="0"} 73
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3533993",proc_name="java",sst_addr="127.0.0.1",ts="0"} 76
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3535261",proc_name="java",sst_addr="127.0.0.1",ts="0"} 92
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3538560",proc_name="java",sst_addr="127.0.0.1",ts="0"} 57
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3539840",proc_name="java",sst_addr="127.0.0.1",ts="0"} 80
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3543344",proc_name="java",sst_addr="127.0.0.1",ts="0"} 88
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3544753",proc_name="java",sst_addr="127.0.0.1",ts="0"} 67
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3549452",proc_name="java",sst_addr="127.0.0.1",ts="0"} 88
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3550734",proc_name="java",sst_addr="127.0.0.1",ts="0"} 92
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3553663",proc_name="java",sst_addr="127.0.0.1",ts="0"} 80
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3555542",proc_name="java",sst_addr="127.0.0.1",ts="0"} 107
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3558523",proc_name="java",sst_addr="127.0.0.1",ts="0"} 73
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3560340",proc_name="java",sst_addr="127.0.0.1",ts="0"} 75
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3564034",proc_name="java",sst_addr="127.0.0.1",ts="0"} 110
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3567808",proc_name="java",sst_addr="127.0.0.1",ts="0"} 109
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3570687",proc_name="java",sst_addr="127.0.0.1",ts="0"} 74
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3572478",proc_name="java",sst_addr="127.0.0.1",ts="0"} 83
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3575567",proc_name="java",sst_addr="127.0.0.1",ts="0"} 68
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3577126",proc_name="java",sst_addr="127.0.0.1",ts="0"} 117
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3580742",proc_name="java",sst_addr="127.0.0.1",ts="0"} 93
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3581876",proc_name="java",sst_addr="127.0.0.1",ts="0"} 89
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3588439",proc_name="java",sst_addr="127.0.0.1",ts="0"} 94
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3590061",proc_name="java",sst_addr="127.0.0.1",ts="0"} 93
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3593581",proc_name="java",sst_addr="127.0.0.1",ts="0"} 112
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3594734",proc_name="java",sst_addr="127.0.0.1",ts="0"} 94
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3598387",proc_name="java",sst_addr="127.0.0.1",ts="0"} 101
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3600367",proc_name="java",sst_addr="127.0.0.1",ts="0"} 92
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3605618",proc_name="java",sst_addr="127.0.0.1",ts="0"} 90
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3606870",proc_name="java",sst_addr="127.0.0.1",ts="0"} 74
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3610162",proc_name="java",sst_addr="127.0.0.1",ts="0"} 100
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3611702",proc_name="java",sst_addr="127.0.0.1",ts="0"} 68
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3615428",proc_name="java",sst_addr="127.0.0.1",ts="0"} 129
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3616587",proc_name="java",sst_addr="127.0.0.1",ts="0"} 90
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3620111",proc_name="java",sst_addr="127.0.0.1",ts="0"} 87
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3623002",proc_name="java",sst_addr="127.0.0.1",ts="0"} 88
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3626537",proc_name="java",sst_addr="127.0.0.1",ts="0"} 88
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3627866",proc_name="java",sst_addr="127.0.0.1",ts="0"} 74
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3631401",proc_name="java",sst_addr="127.0.0.1",ts="0"} 80
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3633034",proc_name="java",sst_addr="127.0.0.1",ts="0"} 102
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3636556",proc_name="java",sst_addr="127.0.0.1",ts="0"} 89
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3638015",proc_name="java",sst_addr="127.0.0.1",ts="0"} 95
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3642618",proc_name="java",sst_addr="127.0.0.1",ts="0"} 108
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3644462",proc_name="java",sst_addr="127.0.0.1",ts="0"} 113
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3647255",proc_name="java",sst_addr="127.0.0.1",ts="0"} 78
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3649158",proc_name="java",sst_addr="127.0.0.1",ts="0"} 68
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3651919",proc_name="java",sst_addr="127.0.0.1",ts="0"} 90
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3653991",proc_name="java",sst_addr="127.0.0.1",ts="0"} 91
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3658332",proc_name="java",sst_addr="127.0.0.1",ts="0"} 138
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3660174",proc_name="java",sst_addr="127.0.0.1",ts="0"} 96
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3663200",proc_name="java",sst_addr="127.0.0.1",ts="0"} 74
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3665160",proc_name="java",sst_addr="127.0.0.1",ts="0"} 110
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3668092",proc_name="java",sst_addr="127.0.0.1",ts="0"} 108
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3669394",proc_name="java",sst_addr="127.0.0.1",ts="0"} 109
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3672832",proc_name="java",sst_addr="127.0.0.1",ts="0"} 105
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3676072",proc_name="java",sst_addr="127.0.0.1",ts="0"} 89
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3679448",proc_name="java",sst_addr="127.0.0.1",ts="0"} 105
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3680826",proc_name="java",sst_addr="127.0.0.1",ts="0"} 91
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3684308",proc_name="java",sst_addr="127.0.0.1",ts="0"} 73
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3685760",proc_name="java",sst_addr="127.0.0.1",ts="0"} 112
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3689462",proc_name="java",sst_addr="127.0.0.1",ts="0"} 91
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3690705",proc_name="java",sst_addr="127.0.0.1",ts="0"} 69
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3695785",proc_name="java",sst_addr="127.0.0.1",ts="0"} 148
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3697228",proc_name="java",sst_addr="127.0.0.1",ts="0"} 107
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3700652",proc_name="java",sst_addr="127.0.0.1",ts="0"} 112
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3701916",proc_name="java",sst_addr="127.0.0.1",ts="0"} 72
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3705372",proc_name="java",sst_addr="127.0.0.1",ts="0"} 95
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3707047",proc_name="java",sst_addr="127.0.0.1",ts="0"} 109
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3711990",proc_name="java",sst_addr="127.0.0.1",ts="0"} 105
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3713196",proc_name="java",sst_addr="127.0.0.1",ts="0"} 136
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3716703",proc_name="java",sst_addr="127.0.0.1",ts="0"} 95
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3718136",proc_name="java",sst_addr="127.0.0.1",ts="0"} 94
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3721699",proc_name="java",sst_addr="127.0.0.1",ts="0"} 111
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3722876",proc_name="java",sst_addr="127.0.0.1",ts="0"} 113
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3726584",proc_name="java",sst_addr="127.0.0.1",ts="0"} 111
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3730176",proc_name="java",sst_addr="127.0.0.1",ts="0"} 82
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3733143",proc_name="java",sst_addr="127.0.0.1",ts="0"} 101
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3734929",proc_name="java",sst_addr="127.0.0.1",ts="0"} 91
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3737943",proc_name="java",sst_addr="127.0.0.1",ts="0"} 90
ebpf_exporter_tcpconnlat_ipv4{dst_addr="127.0.0.1",dst_port="33467",family="2",pid="3740069",proc_name="java",sst_addr="127.0.0.1",ts="0"} 109

**Comment by bobrik** [comment]
You are not supposed to create metrics with high/unbound cardinality with prometheus.

There isn't anything special about `ebpf_exporter` here and the same principle applies to metrics you would export natively from your service. Just removing `pid` would go a long way in your specific case.
