### ISSUE TITLE
Want to add ebpf exporter helm charts to clouflare

### ISSUE THREAD

**Issue by dongjiang1989** [cloudflare/ebpf_exporter#217]
@bobrik ,
I have a separate repo for helm charts for ebpf exporter. like: https://github.com/kubeservice-stack/kubservice-charts/tree/master/charts/kubeservice-ebpf-exporter

I want to add this helm repo to cloudflare community and keep the version consistent. Is it possible to add a related repository？

**Comment by bobrik** [comment]
I can add a link to the README if you switch the docker image to the one we provide:

* https://github.com/cloudflare/ebpf_exporter/pkgs/container/ebpf_exporter

**Comment by dongjiang1989** [comment]
> I can add a link to the README if you switch the docker image to the one we provide:
> 
> * https://github.com/cloudflare/ebpf_exporter/pkgs/container/ebpf_exporter

change image mirror source:
https://github.com/kubeservice-stack/kubservice-charts/pull/18 

https://artifacthub.io/packages/helm/kubservice-charts/kubeservice-ebpf-exporter

**Comment by bobrik** [comment]
I opened #336.
