### ISSUE TITLE
Does the tool support per-cpu array / maps?

### ISSUE THREAD

**Issue by raghu-nandan-bs** [cloudflare/ebpf_exporter#220]
looking at [this](https://github.com/cloudflare/ebpf_exporter/blob/master/exporter/exporter.go#L363) it seems like reading and processing values from per-cpu arrays/maps are not supported. Can you please confirm if this is correct?

if they are indeed not supported, was it a design decision to not consider per-cpu maps?

**Comment by raghu-nandan-bs** [comment]
Thanks @bobrik 

collected data from functions like `netif_receive_skb` requires that we use per cpu counters so that we dont run into race conditions. I wish we could export this as per-cpu metric... Also, the intention is to track "microburst"s so another problem I'm running into is tracking max per "x" millisecond values over a scrape interval. 

Please let me know if you have a solution in mind.

**Comment by bobrik** [comment]
It seems like there are two use-cases:

1. Collect a metric per cpu and export it per cpu.
2. Collect a metric per cpu, but  export it as a combined counter.

It sounds like you want the former. I can see some people wanting the latter, so we should probably support both.

> Also, the intention is to track "microburst"s so another problem I'm running into is tracking max per "x" millisecond values over a scrape interval.
> Please let me know if you have a solution in mind.

This sounds like an interesting non-trivial example we might want to have in the repo. I don't have a solution for this off the top of my head, but please file a separate issue for this. If you already have a non-ebpf_exporter based solution, it would be good to attach it there for a reference.

**Comment by raghu-nandan-bs** [comment]
Thanks for the response @bobrik , will get back

**Comment by bobrik** [comment]
Please take a look at #226 for per cpu map support.

**Comment by raghu-nandan-bs** [comment]
thanks @bobrik ! will check
