### ISSUE TITLE
why don't Port bcc libbpf-tools to ebpf_exporter example 

### ISSUE THREAD

**Issue by cdkunsong** [cloudflare/ebpf_exporter#246]
hi,
For ebpf_exporter, I would like to ask a question:
I see that ebpf_exporter supports bpf related, 
for https://github.com/iovisor/bcc/tree/master/libbpf-tools，it have some good metrics example.
Why ebpf_exporter don't integrated libbpf-tools.
From the code point of view, it is possible, is there any other reason?

**Comment by cdkunsong** [comment]
yes, I checked biolatency.bpf.c, it references https://github.com/iovisor/bcc/blob/master/libbpf-tools/biolatency.bpf.c
What I want to know is why the inclusion of other related bpf programs is not considered? 
Of course, it has some work to do.

commit e06bb8a353e775e412c5e0412e01cbc42772959b
Author: Ivan Babrou <github@ivan.computer>
Date:   Sat Oct 15 18:48:29 2022 -0700

    Port major examples to libbpf

diff --git a/examples/biolatency.yaml b/examples/biolatency.yaml
new file mode 100644
index 0000000..7b0f812
--- /dev/null
+++ b/examples/biolatency.yaml
@@ -0,0 +1,35 @@
+programs:
+  # Block IO latency with tracepoints. See:
+  # * https://github.com/iovisor/bcc/blob/master/libbpf-tools/biolatency.bpf.c

**Comment by bobrik** [comment]
The included programs are _examples_, they are not the exhaustive set of what you can have. We add what we use and we certainly don't have the time to port every `libbpf-tools` program out there.

**Comment by cdkunsong** [comment]
Thank you for your answer!

**Comment by cdkunsong** [comment]
I have understood the situation,close issue.
