### ISSUE TITLE
How to parse union type on yaml

### ISSUE THREAD

**Issue by cdkunsong** [cloudflare/ebpf_exporter#250]
Hi, 
I have a question about ebpf_exporter ask you
For bcc libbpf-tools,for ipv4/ipv6, it use union type.
struct event {
        union {
                __u32 saddr_v4;
                __u8 saddr_v6[16];
        };
        union {
                __u32 daddr_v4;
                __u8 daddr_v6[16];
        };
Have you ever used, how to define the yaml file to parse it(ipv4/ipv6)?
I only found one issue, use two metric for ipv4/ipv6
https://github.com/cloudflare/ebpf_exporter/issues/46

whether have other method?
Thanks!

**Comment by bobrik** [comment]
A struct is just a bunch of bytes and there is no way of knowing which union type you expect to use for decoding.

You need separate configurations for IPv4 and IPv6. I'll add an example.

**Comment by bobrik** [comment]
See #251.

**Comment by cdkunsong** [comment]
@bobrik 
Thanks for sharing! I will close the issue.
