### ISSUE TITLE
Failure in 'make build'

### ISSUE THREAD

**Issue by havefuncoding1** [cloudflare/ebpf_exporter#261]
Hi, I was following instructions in [README.md](https://github.com/cloudflare/ebpf_exporter/blob/master/README.md) to build the project, and 'make build' kept failing with error below:
```
# github.com/aquasecurity/libbpfgo
In file included from ../../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.9-libbpf-1.2.0.0.20230724123347-7e47ce85fbec/libbpfgo.go:5:
./libbpfgo.h:17:10: fatal error: bpf/bpf.h: No such file or directory
        17 | #include <bpf/bpf.h>
           |          ^~~~~~~~~~~
```
Can someone tell me where the problem might be? Thanks.

**Comment by bobrik** [comment]
You don't have `libbpf-dev` (or an equivalent package for your system) installed.

**Comment by havefuncoding1** [comment]
Hi @bobrik thanks for the help. With libbpf-dev installed, build failure for missing bpf/bpf.h is gone, but now there are other errors like below. Is there a different documentation available to setup dev environment and build the project? The [README](https://github.com/cloudflare/ebpf_exporter/blob/master/README.md) doesn't seem to capture enough details about it. It does have a link to this [INSTALL.md](https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---binary), but for Ubuntu, it just says to run "sudo apt-get install bpfcc-tools linux-headers-$(uname -r)". Thanks.

```
gcc errors for preamble:
In file included from ../go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.9-libbpf-1.2.0.0.20230724123347-7e47ce85fbec/libbpfgo.go:5:
./libbpfgo.h: In function
./libbpfgo.h:86:12: error: 'struct perf_buffer_opts' has no member named 'sz'
86 |     pb_opts.sz = sizeof(struct perf_buffer_opts);
   |            ^     
```

**Comment by bobrik** [comment]
What version of libbpf do you have installed? Can you build in docker instead?

**Comment by bobrik** [comment]
I've clarified libbpf related instructions and removed the link to INSTALL.md in #262.

**Comment by havefuncoding1** [comment]
Here is from 'apt list | grep libbpf', and I am running Ubuntu 20.04
```
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libbpf-dev/focal-updates,now 1:0.5.0-1~ubuntu20.04.1 amd64 [installed]
libbpf0/focal-updates,now 1:0.5.0-1~ubuntu20.04.1 amd64 [installed,automatic]
libbpfcc-dev/focal 0.12.0-2 amd64    
```
Build seems to be working with docker. Unfortunately, building examples with command "make -C examples clean build" is broken.
```
clang -mcpu=v3 -g -O2 -Wall -Werror -D__TARGET_ARCH_x86  -idirafter /usr/local/include -idirafter /usr/lib/llvm-10/lib/clang/10.0.0/include -idirafter /usr/include/x86_64-linux-gnu -idirafter /usr/include -I../include/x86 -c -target bpf tcp-window-clamps.bpf.c -o tcp-window-clamps.bpf.o
In file included from tcp-window-clamps.bpf.c:4:                                                                                                                                                                 ./maps.bpf.h:3:28: error: implicit declaration of function 'bpf_map_lookup_elem' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
   u64 zero = 0, *count = bpf_map_lookup_elem(map, key);    
```

**Comment by bobrik** [comment]
v0.5.0 is definitely older than v1.0.0, so no wonder it's not building. I'm fairly sure you need a newer libbpf for examples too.

**Comment by havefuncoding1** [comment]
I think I know where the problem is. According to [this](https://launchpad.net/ubuntu/+source/libbpf), only version available to Ubuntu 20.04 is 0.5.0. Version > 1.0 is for 23.04 or 23.10. So take advantage of ebpf_exporter, I need to upgrade my os.

![image](https://github.com/cloudflare/ebpf_exporter/assets/142353366/74de58b1-cab8-41d3-8c6a-2ce7b3d75f21)

**Comment by bobrik** [comment]
You don't need `libbpf` at runtime. You can build both `ebpf_exporter` and examples in docker (or on another machine with a newer toolchain) and use that on your existing system.

**Comment by havefuncoding1** [comment]
I thought libbpf version needs to match with target environment where ebpf_exporter is running. No?

**Comment by bobrik** [comment]
Only in dynamically linked builds. By default we produce a statically linked binary that doesn't require `libbpf` at all.

**Comment by havefuncoding1** [comment]
I will give it a try. Thanks a lot @bobrik
