### ISSUE TITLE
Providing all binaries as tarball in releases

### ISSUE THREAD

**Issue by jrauschenbusch** [cloudflare/ebpf_exporter#308]
It would be pretty good if there would be GitHub releases including the **ebpf_exporter** binary together with pre-built **examples** in a common tarball for both architectures instead of just the ebpf_exporter binary. Advantage would be to allow pre-compiled binaries directly out of VMs in case the provided functionality of the examples would be totally enough for the specific use case.

Furthermore for the **cachestat** example it would be good to have a 2nd version for kernels <5.15 in the examples folder which still uses `account_page_dirtied` instead of `folio_account_dirtied`.

**Comment by bobrik** [comment]
We provide docker images if you want to run some prebuilt examples. I suppose we can make a github action to upload both compiled examples and binaries to releases.

> Furthermore for the cachestat example it would be good to have a 2nd version for kernels <5.15 in the examples folder which still uses account_page_dirtied instead of folio_account_dirtied.

Please make a PR.

**Comment by bobrik** [comment]
Implemented in #325:

<img width="1080" alt="image" src="https://github.com/cloudflare/ebpf_exporter/assets/89186/3945f55b-79dd-4f59-aa11-d3fe60c83242">

I'll attach these to the next release.
