### ISSUE TITLE
Precompiled release binary

### ISSUE THREAD

**Issue by paulfantom** [cloudflare/ebpf_exporter#32]
Could you provide a binary and a release?

I am writing ansible role for this exporter and it would be really beneficial if there was a binary package somewhere.

**Comment by andrewhowdencom** [comment]
I ran into this issue attempting to run the aforementioned Ansible role :sweat_smile: pretty excited about this one!

**Comment by bobrik** [comment]
I've had some issues with static binaries, but dynamic binary is now attached to the first release:

* https://github.com/cloudflare/ebpf_exporter/releases/tag/v1.0.0

You need to install `libbcc` for your distro to make this work. It should be enough to unblock you.

**Comment by andrewhowdencom** [comment]
> I've had some issues with static binaries

I *think* I tracked this down (in Debian stretch) to there being no static library for libbcc. I couldn't figure out how to compile that statically lol; if you do figure it, id' be super curious how so I can learn.

**Comment by paulfantom** [comment]
Thanks @bobrik.

This really unblocked me and now [my ansible role](https://github.com/cloudalchemy/ansible-ebpf-exporter) is somewhat working, at least it is installing libbcc and this exporter along with systemd file.

Closing this since there is a binary package in place.
