### ISSUE TITLE
objdump generates "unable to initialize decompress status for section .debug_aranges" on v2.3.0

### ISSUE THREAD

**Issue by rob-scheepens** [cloudflare/ebpf_exporter#338]
When running objdump -g on the binary for v2.3.0 it gives an error:
```
nutanix@NTNX-21SM5B060138-A-CVM:10.56.68.161:~$ objdump -g /usr/local/nutanix/bin/ebpf_exporter.x86_64
objdump: /usr/local/nutanix/bin/ebpf_exporter.x86_64: unable to initialize decompress status for section .debug_aranges
objdump: /usr/local/nutanix/bin/ebpf_exporter.x86_64: unable to initialize decompress status for section .debug_aranges
objdump: /usr/local/nutanix/bin/ebpf_exporter.x86_64: File format not recognized
nutanix@NTNX-21SM5B060138-A-CVM:10.56.68.161:~$
```

It seems to be related to the version of binutils used, see for example https://wiki.gentoo.org/wiki/Project:Toolchain/Binutils_2.32_upgrade_notes/elfutils_0.175:_unable_to_initialize_decompress_status_for_section_.debug_info:

"To fix it you need to switch active binutils to sys-devel/binutils-2.32 (and to >=gdb-8.3) or above and rebuild the affected packages."

**Comment by bobrik** [comment]
It sound like binutils is too old on your end. The binaries are built in Debian Bookworm and it has binutils v2.40:

* https://packages.debian.org/search?keywords=binutils

I can replicate the issue even by running binutils v2.31 from Buster (on aarch64):

```
ivan@vm:/tmp$ curl -sLo ebpf_exporter.aarch64 https://github.com/cloudflare/ebpf_exporter/releases/download/v2.3.0/ebpf_exporter.aarch64

ivan@vm:/tmp$ docker run --rm -it -v $(pwd):$(pwd) -w $(pwd) debian:buster bash -c "apt-get update && apt-get install -y binutils && objdump -g ./ebpf_exporter.aarch64" | head -n50
...

./ebpf_exporter.aarch64:     file format elf64-littleaarch64

Contents of the .eh_frame section:
```

**Comment by rob-scheepens** [comment]
You're right, verified this again and I will update our binutils.
