### ISSUE TITLE
examples/ext4dist.bpf.c seems to have too few entries allowed in the latency map 

### ISSUE THREAD

**Issue by siebenmann** [cloudflare/ebpf_exporter#371]
examples/ext4dist.bpf.c appears to specify the maximum capacity of the ``ext4_latency_seconds`` hash map as ``MAX_LATENCY_SLOT + 1`` entries. However, the code seems like it will try to store up to that many separate bucket entries for each separate file operation (so ``MAX_LATENCY_SLOT`` entries for reads, and again for writes, and so on). This seems like it doesn't fit in the maximum entries, and I believe it explains some oddities I saw in actual use that went away when I updated this to multiply the limit by the number of operations. Since I'm inexperienced with eBPF programming, I may be missing something here.

If this is a real bug, it seems likely that this lack of accounting for multiple operation types may exist in other examples as well. In some cases, such as biolatency.bpf.c, this may be normally camouflaged by the fact that few people have anywhere near 255 disks, so the extra space for unused disks compensates for the lack of accounting for the various operations for most people (with modest numbers of disks).

**Comment by bobrik** [comment]
You are right. Would you like to make a PR to fix this?

cc @alebsys

**Comment by siebenmann** [comment]
Unfortunately I feel I don't know what the right fix for this would be. Define a new enum element at the end, called maybe ``F_MAX``, and multiply by that in the ``max_entries`` definition?

(Fixing things like biolatency.bpf.c looks even trickier since the possible req_ops values are non-contiguous, with ``REQ_OP_LAST`` set to 36 but only 14 REQ_OP_* values currently defined.)

**Comment by bobrik** [comment]
> Define a new enum element at the end, called maybe F_MAX, and multiply by that in the max_entries definition?

That's what I would do.

For biolatency you can add a new `define` in ebpf code itself with the number of ops we actually use.
