### ISSUE TITLE
RFE: The path to the pci.ids database should be configurable by a command line switch

### ISSUE THREAD

**Issue by siebenmann** [cloudflare/ebpf_exporter#377]
decoder/pci.go currently hard-codes the file of the PCI IDs database to /usr/share/misc/pci.ids. However, not all Linux distributions put it in that location; Fedora places it in /usr/share/hwdata/pci.ids, and I believe this is followed by current versions of Red Hat Enterprise/CentOS/etc (it is certainly the case on CentOS 7). A command line switch would allow this to be adjusted on a system by system basis, and also allow people to substitute their own more up to date PCI ID databases on older versions of long term support releases that may have old ones.

Based on a quick look at the code this might require significant restructuring, since the in-program PCI database is currently initialized in an init() function (which also means it's loaded immediately on program startup, whether or not it will be needed by any program configured). I suspect such a restructuring is best undertaken by a core author who has a solid idea of how the result should fit into the exporter's overall structure and usage of its modules.

**Comment by bobrik** [comment]
We can do an ordered lookup with the first available file being used:

1. `--config.dir` — a user can place an updated db file or a symlink there
2. `/usr/share/misc/pci.ids` for Debian/Ubuntu
3. `/usr/share/hwdata/pci.ids` For Fedora/RedHat/CentOS

This way there wouldn't be a need for a major code restructuring and thing would work out of the box for most users with no need to introduce any new command line arguments.

**Comment by bobrik** [comment]
> `--config.dir` — a user can place an updated db file or a symlink there

This wouldn't work in `init()`.

**Comment by bobrik** [comment]
I added support for `/usr/share/hwdata/pci.ids`, which feels like should cover 99% of the cases. Let me know if you think otherwise.
