### ISSUE TITLE
How to turn off caching in decoder

### ISSUE THREAD

**Issue by MoonHyuk** [cloudflare/ebpf_exporter#441]
We are going to create a custom decoder, and the decoded values ​​can often change. 
Is there any way to disable decoder caching? Thanks.

**Comment by bobrik** [comment]
Can you be a bit more specific about your decoder? What does it decode that values change?

**Comment by MoonHyuk** [comment]
@bobrik 
For example, we use our internal API to convert an IP address into a hostname, which can change over time.

**Comment by MoonHyuk** [comment]
Perhaps using Prometheus relabeling might be a better approach.
