### ISSUE TITLE
Load eBPF from a file (and not embedded in the YAML)

### ISSUE THREAD

**Issue by amitn** [cloudflare/ebpf_exporter#58]
Would like to have the option to load eBPF program from a file and not embedded in the YAML.

I found it useful when having the same eBPF shared with a Python bcc then you can have something like:
```
#!/usr/bin/python3
from bcc import BPF
b = BPF(src_file="my_ebpf_program.c")
```

And:
`config.yaml`:
```
programs:
    - name: my_program
        file: my_ebpf_program.c
```
`ebpf_exporter --config.file=config.yaml`

I have created the change amitn/ebpf_exporter@f99ac6fb8634fc7e807603ba7b62712869988837

What I'm not sure about, from usability point of view, is how to handle relative path, from execution or from configuration

**Comment by bobrik** [comment]
Do you have a sample program that you use in this manner (from exporter and somewhere else)?

**Comment by bwplotka** [comment]
This is great, but I think this is could be much more useful if we would be able to add multiple file's projects. E.g I have couple of headers with extra helpers that I would love to load and import with the program.

**Comment by bwplotka** [comment]
Actually ignore, me I can import just fine using cflags: e.g

```
    cflags:
      - -I/shared/data/ebpf_exporter/include
```

**Comment by bwplotka** [comment]
I guess this will work for @amitn case too (:
