### ISSUE TITLE
grafana example charts

### ISSUE THREAD

**Issue by aleks-mariusz** [cloudflare/ebpf_exporter#59]
it's great you folks [a few example configs](https://github.com/cloudflare/ebpf_exporter/tree/master/examples) for the exporter.. however since you demonstrate a lovely grafana graph graphing the metrics (say that 5 times fast), it would really *swell* if you _also_ included the dashboard definition JSON that creates those exact grafana graphs.. 

p.s.. a [quick search](https://grafana.com/grafana/dashboards?search=ebpf) on the official grafana dashboard collection shows exactly 0 sample charts, could you please create some ?

**Comment by bobrik** [comment]
That's not something we intend to provide.

**Comment by dongjiang1989** [comment]
@aleks-mariusz   grafana dashboard : [https://grafana.com/grafana/dashboards/18612-kernel-ebpf-hook/](https://grafana.com/grafana/dashboards/18612-kernel-ebpf-hook/)

helm install : [https://artifacthub.io/packages/helm/kubservice-charts/kubeservice-ebpf-exporter](https://artifacthub.io/packages/helm/kubservice-charts/kubeservice-ebpf-exporter)
