### ISSUE TITLE
runqlat needs an update for newer kernels

### ISSUE THREAD

**Issue by vedranf** [cloudflare/ebpf_exporter#71]
Hello,

When trying to run runqlat example I'm getting something like:

failed to attach kprobes: failed to attach probe "ttwu_do_wakeup" to "trace_ttwu_do_wakeup": failed to attach BPF kprobe

however original bcc tool runqlat still works. Apparently this issue was fixed in:

https://github.com/iovisor/bcc/commit/0d72237946afebc5d300676af641319fb3d020be#diff-0d3cbd144510f7be0e8837764d7ec90a

so I assume it needs a fix here as well.

Regards,
Vedran

**Comment by bobrik** [comment]
Thanks for pointing this out. Lack of stable interface is the fact of life with `kprobe`, that's why we have both `kprobe` and `raw_tracepoint` variants of the `timers` example.

PR is welcome to migrate `runqlat` example, so I'll leave this open in case anyone wants to try.

**Comment by bobrik** [comment]
We now use libbpf, so this should be easier. There hasn't been much interest in this so far, so I'm going to close it.
