### ISSUE TITLE
Feature request: Helm Chart and Docker image

### ISSUE THREAD

**Issue by maxenglander** [cloudflare/ebpf_exporter#82]
Hello!

We are starting to use this in our Kubernetes worker nodes. We are using https://github.com/vanneback/ebpf_exporter_helm (plus [several fixes](https://github.com/vanneback/ebpf_exporter_helm/pulls?author=maxenglander)) to deploy it. Unfortunately, that chart does not seem to be actively maintained, and, as far as I can tell, there is no authoritative, well-maintained image on DockerHub for ebpf_exporter.

It would be great if there was an authoritative Helm chart and Docker image for this project. What do you think? If you like the idea, I'd be happy to contribute.

Thanks :)

**Comment by bobrik** [comment]
Packaging it in a docker container is tricky, you end up doing things like this:

* https://github.com/vanneback/ebpf_exporter_dockerfile/blob/782fd0bac75b5be49ef/entrypoint.sh#L2

Or having to bind mount a lot of things from the host. It gets trickier when you start thinking about multiple host distros (people running CentOS for example) or cases when they may have kernels not available in repos of the image (we have our internal kernel in internal repos).

At Cloudflare we run `ebpf_exporter` directly on the host to avoid all these issues, which means that we'd have to carry code we don't necessarily exercise. I think it may be easier to keep Docker image external for now.

**Comment by maxenglander** [comment]
Agree that it's a bit hacky to `apt-get install linux-headers`, and gets brittle quickly. I can also understand not wanting to maintain a Docker image / Helm chart when that's not something Cloudflare has internal use for.

FWIW, I think bind-mounting kernel source/headers is relatively light-weight operationally, and less brittle. We try to keep our hosts as "dumb" as possible, and put as much logic as we can in K8S, in part because we like the API and operational mechanics of it more than we like our host-management tooling.

For a Helm chart, I think one could take a "batteries not included approach", and require users to either mount volumes (which are commonly configurable in charts for infra components) and/or supply a command or entrypoint that installs the needed. files via package manager, wget from internal repo, etc.

**Comment by bobrik** [comment]
Now that we switched to libbpf, the amount of stuff you need to bind-mount is very manageable (it can be zero).

I opened #153 to add a docker image.

**Comment by bobrik** [comment]
Helm chart note: #336.
