### ISSUE TITLE
Linting: Move from gometalinter to golanci-lint

### ISSUE THREAD

**Issue by mjtrangoni** [cloudflare/ebpf_exporter#87]
Hi @bobrik,

[gometalinter](https://github.com/alecthomas/gometalinter) is deprecated. See [#590](https://github.com/alecthomas/gometalinter/issues/590).

If you agree, I can create a PR for switching from [gometalinter](https://github.com/alecthomas/gometalinter) to [golangci-lint](https://github.com/golangci/golangci-lint) on TravisCI.

**Comment by bobrik** [comment]
Thanks for reminding, it's done in #89 along with more ergonomic Github actions.
