### ISSUE TITLE
Add option to load multiple config files

### ISSUE THREAD

**Issue by yzgyyang** [cloudflare/ebpf_exporter#94]
Hi! I would like to have the option to load multiple config files here, to:

- avoid the config YAML file which consists of all possible eBPF programs becoming too lengthy
- be able to reuse eBPF programs in different environments (for example, only run some programs for server1, and some other for server2, without copy-pasting individual programs to individual config files for each server)
- be able to quickly specify which eBPF programs to run

I think there are a couple of possible ways to take here (without breaking the existing interfaces):

1. Similar to `--config.file <file>`, add a `--config.files <file1>,<file2>,<file3>` to allow multiple config files being loaded at the same time. (Even better, accept a globbing pattern here)
2. For a giant config file, add a `--config.programs <program1>,<program2>` to only run certain eBPF programs.
3. Achieve this through YAML level maybe? Something like 

```yaml
programs:
  - program_path: ./config1.yml
  - program_path: ./config2.yml
```

I would like to know which route you guys prefer if I were to help implement this feature, thanks! @bobrik

**Comment by bobrik** [comment]
Prometheus exporters generally allow a single config file and let configuration management figure out what machines get what kinds of configs. That's what we do internally at Cloudflare as well. I don't think that some convenience for manual config management is a good reason to support multiple configs and diverge from an established pattern.

There's #58 to allow loading code from external files.
